name:                cft
version:             0.1.0.0
github:              "codeleventh/cft"
license:             BSD3
author:              "codeleventh"
maintainer:          "eleventh@vechnost-eto-ne-srok.ru"
copyright:           "2018 codeleventh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/codeleventh/cft#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative

library:
  source-dirs: src

executables:
  cft-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cft

tests:
  cft-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cft
